development:
  adapter: mysql2
  database: articles3
  host: localhost
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: articles3-test
  host: localhost
  username: root
  password:
  encoding: utf8
